### ISSUE TITLE
Me again, Pciescreamer doesn't get detected on target system

### ISSUE THREAD

**Issue by tiltmasteR** [ufrisk/pcileech-fpga#10]
Me again :(

Error on my sie sry...

**Comment by ufrisk** [comment]
That is normal. No driver is required on the target system for this to work.

**Comment by tiltmasteR** [comment]
Rip, the i have to dive more into it as it didn't work then. K thanks Just delete this here.

**Comment by ufrisk** [comment]
Some times it may work if you cold boot your system; but in your case the target system seems to detect the device so I think it should work.

**Comment by tiltmasteR** [comment]
IT works, Even though only after i shutdown my PC. On reboot the Board doesnt get detected tho

**Comment by ufrisk** [comment]
Thanks for letting me know. Good luck with everything. The rebooting problem might be because the PCIeScreamer is not always 100% stable.

**Comment by tiltmasteR** [comment]
Exactly It stops working once i try to write memory :/ but reading works perfectly fine
