### ISSUE TITLE
LiteFury flashing problem

### ISSUE THREAD

**Issue by Berniokas** [ufrisk/pcileech-fpga#100]
Hello,
I had a problem with connecting to LiteFury with Digilent HS2 adapter for flashing Pcileech to it. Vivado Hardware manager can't detect HS2 and LiteFury board. I using original LiteFury JTAG cable. Digilent drivers are installed and in FT_Prog program HS2 cable is detected. Did I need to change any settings in FT_Prog? Current HS2 settings are attached in screenshots.  
Thank you in advance.
Best regards
![Screenshot 2022-04-15 120528](https://user-images.githubusercontent.com/103743168/163563879-d47f3ea6-504a-49ce-ade3-0e03429c51ec.png)
![Screenshot 2022-04-15 120603](https://user-images.githubusercontent.com/103743168/163563890-364e9364-6f4e-4135-be51-7c843d088d30.png)
![Screenshot 2022-04-15 120626](https://user-images.githubusercontent.com/103743168/163563891-e23873c8-1b1a-4c14-a50f-5ea5de984b53.png)
![Screenshot 2022-04-15 120651](https://user-images.githubusercontent.com/103743168/163563893-8bc88151-f2ea-4029-be1d-c7b46928aa49.png)
![Screenshot 2022-04-15 120716](https://user-images.githubusercontent.com/103743168/163563894-49cb17ad-e985-4909-8eed-e95e82e1f553.png)
![Screenshot 2022-04-15 120744](https://user-images.githubusercontent.com/103743168/163563895-fcf211ab-58ab-4313-9ea9-673a19bd881f.png)

Marek

**Comment by ufrisk** [comment]
hm, for flashing with the HS2 you should not change anything in the FT_Prog. I never did ever. Make sure the HS2 is connected as I show here: https://lh3.googleusercontent.com/-2vfVlTj7pn4/YWbocqUV_7I/AAAAAAAAAa0/o-vWEZ2JPkwXZ60DdXDonRGgznqkvj1mgCLcBGAsYHQ/s1600/jtag-1.jpg and also that the LiteFury is powered by itself. It should be detected automatically by vivado when connecting to the HS2.

**Comment by ufrisk** [comment]
I'm assuming this issue was resolved. Closing the open issue. If you still have any questions please let me know in this thread.
