### ISSUE TITLE
Can't build firmware for PCIeSquirrel

### ISSUE THREAD

**Issue by he4rtbleed** [ufrisk/pcileech-fpga#106]
![image](https://user-images.githubusercontent.com/29333455/180646511-83bb7987-b7fe-4959-b90b-2644934223cd.png)

when i build in vivado it shows following error but idk what is it
same at tcl shell

**Comment by ufrisk** [comment]
It's working for me.

1. which Vivado version are you using?
2. which OS are you building on?
3. is this the default bitstream or did you do any customization to the source code and/or config?

**Comment by he4rtbleed** [comment]
i moved folder to C:\ root and it works

**Comment by ufrisk** [comment]
Thanks for the update. Yeah, I forgot about that there is a long path limitation on Windows. I should add that to the guide. Thanks for the update and getting back to me.
