### ISSUE TITLE
Need clarification for Access mode for SP605/FT601 device connected 

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech-fpga#108]
Hi frisk,

I have noticed that "Access mode" DMA (hardware only) and Normal . what is the difference between this ?

I recently downloaded PCIleech binaries files and connected  64bit SP605 /FT601 device. While dumping the memory,We seen always --> Access mode is Normal.

While running with my old pcileech binaries files . Getting below as pic. ( "Access mode" DMA (hardware only))

![image](https://user-images.githubusercontent.com/97678866/184061999-4fa55535-1bc0-40ab-a3da-ee55cd641923.png)

While running with newly downloaded pcileech binaries files(V4.15) . Getting below as pic. "Access mode" is Normal

![image](https://user-images.githubusercontent.com/97678866/184062130-cf8872a8-790b-4bc4-a716-8ea1f8ff02af.png)

Why is this different results shown here  ?

**Comment by ufrisk** [comment]
I changed the description text. It's no difference.

**Comment by sridhaleech** [comment]
Ohh! Thanks Frisk.
So we run the test with "Access mode : Normal" right  ?
