### ISSUE TITLE
Does SP605 support the latest pcileech 4.XX

### ISSUE THREAD

**Issue by uk0** [ufrisk/pcileech-fpga#114]
Hi, I want to know if the SP605-FT601 will work fine with the latest pcileech 4.11

thx  ufrisk ：）

**Comment by ufrisk** [comment]
Hi and many thanks for the sponsorship.

I haven't upgraded the SP605 to the v4.11 firmware since the development environment for it is quite horrible to work with.

The SP605 firmware (2.2 if I remember correctly) should work fine with the current PCILeech though, but it will be somewhat limited.

**Comment by uk0** [comment]
ok
