### ISSUE TITLE
issues with vivado building and other stuff

### ISSUE THREAD

**Issue by nascarZ** [ufrisk/pcileech-fpga#117]
Hello, so ive been trying to get started and im having issues with general building and trying to edit stuff
![image](https://user-images.githubusercontent.com/122063988/210903785-49092f48-ac46-44bc-89cb-cd73f2006803.png)
![image](https://user-images.githubusercontent.com/122063988/210903806-c42fa657-dfd9-45d9-a548-e92e371e9f66.png)
when trying to run the build
to just break down what i did:
opened vivado _> Window tab -> Tcl console -> cd into my pciesquirrel folder and run the vivado generate project -> then i click add sources on project manager -> add or create design sources -> src and ip folders i got in the pciesquierel folder from the zip -> and then run in console prompt vivado_build.tcl-notrace and after a couple minutes just errors with some files...
And on top of that when i did try modifying the pcie_7x_0.xci like said in build.md it says the pcie_7x_0.xci is IP locked.
![image](https://user-images.githubusercontent.com/122063988/210904419-c2dd6a21-c82a-4f13-af26-93bdef30a976.png)
i tried searching and stuff but i couldnt really find anything.. any help?

**Comment by nascarZ** [comment]
nvm im dumb

**Comment by ufrisk** [comment]
I'm glad to see you managed to resolve the issue without any help. closing the issue.
