### ISSUE TITLE
What about LurkerDMA?

### ISSUE THREAD

**Issue by StarSherron** [ufrisk/pcileech-fpga#120]
What firmware can be loaded into LurkerDMA?
I wanted to connect via vivado, but she sees the cable connected to the update port as COM3.

thanks in advance for your reply!

**Comment by ufrisk** [comment]
Apologies, I unfortunately do not know about about that. I don't have access to a LurkerDMA board and I'm not too keen on purchasing one just to test it out since I already have quite a few other boards.

Can you please contact the seller about how he set up the LurkerDMA with regards to updating?
