### ISSUE TITLE
Modifying CFG space

### ISSUE THREAD

**Issue by Haseeb18P** [ufrisk/pcileech-fpga#129]
Hey, is it possible to modify blocks 40, 60 & 70 in the cfg space? Would you be able to give me any instructions on how I can achieve this?

**Comment by ufrisk** [comment]
I know people have been modifying the .xci file directly that generates the PCIe core. Also the generated core sources.

But I have not looked into this myself so I can't really help more than this in this matter.

**Comment by Haseeb18P** [comment]
Would you happen to know the exact name of the .xci file that generates the PCIe core?

**Comment by ufrisk** [comment]
https://github.com/ufrisk/pcileech-fpga/blob/master/PCIeSquirrel/ip/pcie_7x_0.xci

**Comment by Haseeb18P** [comment]
After looking at the documentation on xilinx, it seems like that the MSI Control is stored at the 40 range, does this also seem like I'm looking in the right direction too you? Thanks in advance!
![image](https://github.com/ufrisk/pcileech-fpga/assets/93434315/5a873df6-40e7-4f2d-a056-64f858aaa0f7)

**Comment by ufrisk** [comment]
Yeah, looks ok to me. This is a long and tedious process though, but best wishes with it 👍
