### ISSUE TITLE
[Squirrel] Flashing but nothing appears in device manager and can't pcieleech

### ISSUE THREAD

**Issue by Youssix** [ufrisk/pcileech-fpga#135]
Hey,

I have an issue with my squirrel dma card.

I am flashing it but it's not working at all, i see nothing in the device manager ?

The led1 is blinking , led 2 off and led 3 ON.

I did flash it , 

when i run : 

PS D:\DMA\Pcieleech> .\pcileech.exe probe -v -device fpga://devreload=1

DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.11,0000]
PCILEECH: Failed to connect to the device.

My middle led blinks then stop.

**Comment by ufrisk** [comment]
The flashing is successful. It's the expected behavior.

You however have a bad PCIe connection for some reason. Try shutting down the PC and then power it up again to see if things have improved.

**Comment by Youssix** [comment]
Are you suggsesting to try another PCIe port ? 

i'll try again then but it was working fine until i try to flash recently with a custom pcileech wifi fw, even when flashing to my old firmware i was using it's still not found in device manager.

the flashing gets right i believe then if you say so , what could be the problem , i already tried many time to reboot the computer already.

**Comment by ufrisk** [comment]
Sometimes the PCIe is not working if you mess up your custom config space enough. The flash seems however to be OK.

You can try to flash the default firmware I provide here on Github to see if it works better and start from there.

Let me know if it works better with the default firmware.

**Comment by Youssix** [comment]
Hello @ufrisk ,

So i just tried it today and i have this result : 

PS D:\DMA\Pcieleech> .\pcileech.exe probe -v -device fpga://devreload=1

DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.12,0000]
PCILEECH: Failed to connect to the device.




Same error, i even tried to switch the pcie lane, nothing helps.



What could be the problem ? the card is dead ?

**Comment by Youssix** [comment]
PS D:\DMA\MemProcFS_files_and_binaries_v5.8.15-win_x64-20231022> .\MemProcFS.exe -v -vv -device fpga

----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-ONLY     SIZE: 40 BYTES -----
0000    89 ab 00 00 28 00 00 00  04 0c 04 00 00 00 00 00   ....(...........
0010    d8 ac b6 60 05 00 00 00  da ac b6 60 05 00 00 00   ...`.......`....
0020    00 00 02 00 ff ff ff ff                            ........

----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-WRITE    SIZE: 30 BYTES -----
0000    cd ef 04 00 1e 00 00 00  a0 86 01 00 00 00 00 00   ................
0010    ee 10 07 00 ee 10 66 06  02 3c 00 00 00 00         ......f..<....

----- PCIe CORE Dynamic Reconfiguration Port (DRP)  SIZE: 0x100 BYTES -----
0000    00 00 00 01 00 02 00 00  00 00 00 00 00 00 f0 00   ................
0010    ff ff 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020    00 00 00 00 00 00 00 00  00 00 00 40 00 00 00 00   ...........@....
0030    00 00 09 02 30 00 22 7f  02 00 01 00 00 03 11 0c   ....0." ........
0040    02 a1 00 43 01 00 1f fd  7f ff 09 ff 01 20 01 48   ...C.... .... .H
0050    00 05 01 60 11 9c 00 00  00 00 00 00 00 00 00 00   ...`............
0060    00 00 10 60 00 02 40 21  00 40 3d 48 00 23 00 00   ...`..@!.@=H.#..
0070    00 00 00 00 00 00 00 00  00 00 00 00 00 15 00 01   ................
0080    00 01 00 00 00 01 00 00  00 01 00 00 00 01 00 00   ................
0090    00 01 00 00 00 01 00 00  00 00 00 00 00 00 00 00   ................
00a0    00 00 00 00 00 00 00 00  00 02 00 00 12 34 10 18   .............4..
00b0    00 0b 00 01 00 11 00 00  00 00 00 00 00 01 00 00   ................
00c0    00 28 00 41 ff ff ff ff  00 e0 00 00 80 08 00 22   .(.A..........."
00d0    07 ff 03 52 02 48 00 08  00 40 0e 84 fa ac 00 00   ...R.H...@......
00e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

----- PCIe SHADOW CONFIGURATION SPACE (only user set values) SIZE: 0x1000 BYTES -----
0000    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0010    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0030    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0040    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0050    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0060    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0070    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0080    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0090    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0100    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0110    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0120    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0130    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0140    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0150    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0160    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0170    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0180    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0190    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
01f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0200    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0210    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0220    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0230    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0240    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0250    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0260    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0270    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0280    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0290    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
02f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0300    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0310    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0320    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0330    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0340    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0350    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0360    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0370    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0380    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0390    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
03f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0400    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0410    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0420    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0430    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0440    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0450    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0460    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0470    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0480    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0490    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
04f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0500    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0510    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0520    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0530    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0540    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0550    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0560    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0570    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0580    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0590    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
05f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0600    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0610    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0620    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0630    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0640    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0650    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0660    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0670    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0680    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0690    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
06f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0700    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0710    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0720    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0730    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0740    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0750    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0760    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0770    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0780    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0790    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
07f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0800    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0810    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0820    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0830    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0840    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0850    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0860    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0870    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0880    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0890    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
08a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
08b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
08c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
08d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
08e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
08f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0900    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0910    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0920    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0930    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0940    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0950    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0960    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0970    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0980    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0990    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
09a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
09b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
09c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
09d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
09e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
09f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a00    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a10    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a20    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a30    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a40    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a50    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a60    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a70    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a80    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0a90    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0aa0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ab0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ac0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ad0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ae0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0af0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b00    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b10    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b20    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b30    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b40    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b50    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b60    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b70    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b80    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0b90    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ba0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0bb0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0bc0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0bd0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0be0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0bf0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c00    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c10    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c20    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c30    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c40    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c50    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c60    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c70    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c80    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0c90    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ca0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0cb0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0cc0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0cd0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ce0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0cf0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d00    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d10    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d20    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d30    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d40    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d50    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d60    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d70    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d80    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0d90    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0da0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0db0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0dc0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0dd0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0de0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0df0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e00    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e10    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e20    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e30    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e40    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e50    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e60    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e70    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e80    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0e90    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ea0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0eb0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ec0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ed0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ee0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ef0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f00    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f10    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f20    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f30    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f40    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f50    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f60    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f70    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f80    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0f90    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0fa0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0fb0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0fc0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0fd0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0fe0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0ff0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.12,0000]
MemProcFS: Failed to connect to memory acquisition device.

**Comment by Youssix** [comment]
![image](https://github.com/ufrisk/pcileech-fpga/assets/16267835/fede3aa2-86e2-4543-99fe-0d574a55cd71)

**Comment by Youssix** [comment]
It seems like a lot of people have this problem no ?

**Comment by Youssix** [comment]
The pcie slot is showed at empty by my motherboard at bios, is it normal ?

**Comment by Youssix** [comment]
Hardware issue, ordered a new one and it works thanks.

**Comment by ufrisk** [comment]
Thanks for the update, I'm glad to see it works now. Best wishes with your DMA attacking.
