### ISSUE TITLE
Does the PCIe Squirrel Card Function During Pre-Boot Stage (MRC or PEI) before Booting Up to DXE or OS phase 

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech-fpga#137]
Hi Frish,

I'm using the PCIe Squirrel 64-bit Card for my testing.

My test scenario involves the system booting in the initial stage( BIOS ) and attempting to perform a DMA attack during stages like PEI (Pre-EFI Initialization Phase) and MRC (Memory Reference Code).

Question 1:
Is it expected that DMA to DRAM will get any meaningful data during the MRC and PEI stages?

Question 2:
How can I confirm whether my PCIe Squirrel card is being really detected during the MRC and PEI stages?

Question 3:
Does the absence of detection in the PCI information below indicate that the PCIe Leech card is not being recognized?

![image](https://github.com/ufrisk/pcileech-fpga/assets/97678866/1e129ec4-8964-4b15-a669-85a6b8990923)

**Comment by ufrisk** [comment]
I haven't researched this topic. But best wishes with your research 👍
