### ISSUE TITLE
PCIe 1x squirrel card (FPGA -3rd party) is not enumerated when we connected Behind Gatkex Creek Card PCIe slot (x4)

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech-fpga#138]
Hi Frisk,

We trying to do DMA over the TB4 dock via the PCIe port .

The problem is  --> Gatkex Creek (dock) card has been enumerated on our testing target System, But behind Gatkex  Card PCIe slot, the connected PCIe 1x squirrel card and the PCIe Leech squirrel card are not enumerated ( No led growing on the card ).

![image](https://github.com/ufrisk/pcileech-fpga/assets/97678866/f4fd5428-cd83-4bf8-84bc-bdb8a9b28e78)

Tried OS -->  Ubuntu OS /Windows OS.
Note: Same PCIe 1x squirrel card connected to the direct target system and detected fine.

Could you suggest any fixes from your end for this issue?

**Comment by ufrisk** [comment]
Thunderbolt boards like that usually don't provide 12V power. You'd need to feed 12V power to the connector. Notice the board is completely dead on the LEDs.

Easiest way is to put a "bitcoin mining" PCIe extender in-between and connect 12V power to it to the Molex/SATA connector it usually have.
