### ISSUE TITLE
Ways to detect current firmware version?

### ISSUE THREAD

**Issue by taylor310** [ufrisk/pcileech-fpga#144]
Is there any way to tell what firmware version your card is using(squirrel? I bought a used card and am curious if I'm still on 4.10 or 4.11.

**Comment by ufrisk** [comment]
It's easiest to check it with pcileech as per below,

![image](https://github.com/ufrisk/pcileech-fpga/assets/18221464/ac9c920b-c7b7-4ee4-abe3-b95bd50dbc50)

**Comment by taylor310** [comment]
Thank you! Sorry for the stupid question.
