### ISSUE TITLE
about memory issue

### ISSUE THREAD

**Issue by CaS1ow** [ufrisk/pcileech-fpga#149]
hi i am using immortaltech.net warrior dma, win10 22h1, 12700kf, 16+16gb ram
name: g.skill ddr4 32g pc4-28800 cl16 trident z royal c

i have a problem with this ram

dma test not work(Error Occurrence)
i tested alot of fw and custom fw and i changed asus mother board to msi motherboard but same issue

checked bios vt-d off,iommu off,fast boot off,secure boot off, csm enable, reinstall window and checked turned on and off xmp

i always do powercycle when install or uninstall dma

here is my error(Two errors depending on the situation)
```
1.
DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [3,v4.9,0000]
MemProcFS: Failed to connect to memory acquisition device.
```
```
2.
[CORE]     Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
[CORE]     Failed to initialize.
```

this errors only showing when i installed gskill ram at my main pc of course dma installed at my main pc

if i change gskill to samsung ram, dma test works fine

so i tried install my dma at 2nd pc, gskill ram installed at my main, and dma test works fine

I thought dma had a compatibility problem with my asus mainboard z690, so I bought a new mainboard from msi z790

I was stressed out for two weeks to fix this, and eventually I tried to replace the RAM and it worked

please give me some advice or if its really ram's problem is sure, i can buy new ram if problem can fix

i think the 2nd pc doesn't seem to be able to get the data from the gskill ram installed pc something block or idk..

gskill ram installed pc's device manager, i cant find any pci device or network device with Yellow exclamation mark

**Comment by CaS1ow** [comment]
please give me some advice
setting bios or just buy new ram will clean my brain..

finally i found how to fix that error but i wanna save my money i thought error's problem was my asus motherboard compatibility so i bought msi but finally found the problem is ram

**Comment by CaS1ow** [comment]
i am using immortaltech.net warrior dma

**Comment by CaS1ow** [comment]
i think i fixed it changed bios
1.memory fast boot disabled
2.security device support disabled

**Comment by CaS1ow** [comment]
ok another problem appear
if i turn on xmp
```
FPGA: TINY PCIe TLP algrithm auto-selected!
LcMemMap_AddRange: 0000000000000000-000000000009ffff -> 0000000000000000
LcMemMap_AddRange: 0000000000100000-00000000ffffffff -> 0000000000100000
LeechCore v2.14.2: Open Device: fpga
[CORE]     Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
[CORE]     Failed to initialize.

[CORE]     SHUTDOWN COMPLETED (0000017BB44D8040).
```
after fresh reboot
```
DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [3,v4.9,0000]
MemProcFS: Failed to connect to memory acquisition device.
```

**Comment by ufrisk** [comment]
I'm not really able to give support on all those 3rd party devices with custom firmware that is sold. They don't contribute anything to my project financially and they just leave me with the support tab unfortunately. Also the custom firmware is having great many unknowns which makes it very hard for me to support.

It's how it is, my projects are open source so it's fine to do this I guess, but I'm not too happy giving out free support out of my time just so that others can earn a lot of money.

Version 4.9 is pretty old though, it's version 4.12 now and there have been a few bug fixes since then.

If it works without XMP can't you just run it that way? The performance gain of XMP isn't massive anyway so just disable it when doing DMA and enable it other wise?
