### ISSUE TITLE
Does the firmware support Kintex 7 Chips?

### ISSUE THREAD

**Issue by xiaonian233** [ufrisk/pcileech-fpga#150]
I have purchased DMA for the XC7K series, models XC7K70T and XC7K325T respectively, but I am not sure if it is compatible with PCilech FPGA firmware. I am a beginner, please forgive my ignorance.

**Comment by ufrisk** [comment]
Pre-built PCILeech firmware isn't directly compatible with Kintex7 but it should be easy to port it.

You'd need to move the design to the new chip and change the PIN constraints in the .XDC file, that's pretty much it.

Also the PCILeech design requires the FT601 USB chip currently. But just purchase a FTDI FT601 USB3 UMFT601X-B add-on board as described in the ac701_ft601 project. This requires you to have a FMC port though.

Best wishes with your project!
