### ISSUE TITLE
Question: Can I effectively use the Screamer PCIe Squirrel in a single PC setup.

### ISSUE THREAD

**Issue by Hypsster** [ufrisk/pcileech-fpga#154]
I would like to customize this firmware and test it out. I only have a single PC, and I've been seeing around that I should be using this with a 2pc setup. 

But I would like to use this for research and learning offline. IS this possible.

**Comment by ufrisk** [comment]
You could use this on 1 PC as well, just connect the USB cable as well.

But you'd need a computer if doing hardware based DMA. It's not possible to do hardware based DMA without a computer or what do you mean? For offline research its more reading specifications etc.
