### ISSUE TITLE
CRITICAL WARNING: [filemgmt 20-1673] 

### ISSUE THREAD

**Issue by finalmouse** [ufrisk/pcileech-fpga#16]
When trying to build the pciescreamer xpr file I get an error after 1-2 minutes

CRITICAL WARNING: [filemgmt 20-1673] Unlinking is not permitted for the source file: 'c:/pcileech-fpga-master/pciescreamer/pciescreamer/pciescreamer.srcs/sources_1/bd/pcileech_vfifo/pcileech_vfifo.bd'

I suppose the build is not completely done? Although I can open the project in Vivado...

**Comment by ufrisk** [comment]
It usually works fine anyway, that "critical warning" aren't really critical.
