### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by hypr1x** [ufrisk/pcileech-fpga#163]
Hello, quick question, how would I get a key press with dma on my second pc?

**Comment by ufrisk** [comment]
This Github is not for asking general questions. It's for reporting issues, having enhancement suggestions etc. But google around for it and I'm sure you'll find some answers :)

You could also join the Discord to ask some quick questions. But talks about game hax and/or anti-cheat bypasses aren't allowed.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
