### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by wilko236** [ufrisk/pcileech-fpga#164]
I'm setting up my DMA 
and when I go to test
I keep coming across this is issue

Failed to refresh MemProcFS - aborting!
[CORE 1
PROCESS_REFRESH: Partial
[PROCESS]
[PROCESS 1
SYSTEM DTB: 00000000001a6000 EPROCESS: ffffd4032a8d04

**Comment by ufrisk** [comment]
This Github is not for asking general questions. It's for reporting issues, having enhancement suggestions etc.

You could also join the Discord to ask some quick questions like this one. But talks about game hax and/or anti-cheat bypasses aren't allowed.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
