### ISSUE TITLE
Leetdma Abnormal speed measurement

### ISSUE THREAD

**Issue by GRRENY** [ufrisk/pcileech-fpga#166]
I successfully produced leetdma using open source leetdma drawings, and successfully burned the squirrel's firmware, but something went wrong during the speed test. When the device is turned on, only the blue indicator flashes once, and the FT601 driver is successfully connected, but when you turn on the speed test to load, it will show that it is not connected to the FPGA device. I asked a lot of people, and they all said that the firmware did not match, but leetdma can burn the firmware of the squirrel normally. I was going crazy with this question, I didn't know what to do.
![1](https://github.com/ufrisk/pcileech-fpga/assets/124686897/c00ba50d-5902-4d7e-aea3-4c0ed5512f06)
![2](https://github.com/ufrisk/pcileech-fpga/assets/124686897/fdfe5be0-5c24-43c9-a936-7fb99be5c7ce)
![3](https://github.com/ufrisk/pcileech-fpga/assets/124686897/a62b3aa0-dfa4-490d-888f-d29e2ebbaf74)

**Comment by GRRENY** [comment]
Interestingly, I can't use the official burner provided by LeetDMA, but I successfully burned the firmware with the burner of HackDMA

**Comment by ufrisk** [comment]
Nice to see you got it to work and congratulations on your new board.

But I'm closing this issue since I don't think successfully creating a board and flashing it is an issue.
