### ISSUE TITLE
Unable to detect Xilinx Ethernet Adapter with Device ID 0x0666

### ISSUE THREAD

**Issue by helloboiss** [ufrisk/pcileech-fpga#17]
Windows 10 is unable to detect my xilinx ethernet adapter. I only have a "Ethernet-controller" with:

Device PCI\VEN_10EE&DEV_0666&SUBSYS_000710EE&REV_02\0000000101000A3500 requires further installation.

It also won't let me change the deviceID etc. Followed all the steps and re-building takes so many time. So any help would be appreciated

**Comment by ufrisk** [comment]
This is the normal behavior. Windows says that it's unable to load a driver and start the device. DMA is still working though.

Also, it's not possible to change the device ID's in device manager in Windows. You have to rebuild the bitstream in the FPGA project to do that. Please consult the advanced build readme for info how to alter the Device ID.

**Comment by Aico89** [comment]
Thanks for the quick answer ufrisk. Already tried to change the Device ID with Vivado HL WebPack 2018.2, but still same DeviceID showing up in device manager. 

Tried also generating the bitstream with Vivado, with no success.

**Comment by helloboiss** [comment]
Thanks for the quick answer ufrisk. Already tried to change the Device ID with Vivado HL WebPack 2018.2, but still same DeviceID showing up in device manager.

Tried also generating the bitstream with Vivado, with no success.

**Comment by ufrisk** [comment]
You will need to rebuild the bitstream with vivado and re-flash the board with the new bitstream using the programming cable for the changes to materialize.

I'll try to look into the build errors in Vivado, unfortunately I do not have any free time to this until next Tuesday (30/10) at the earliest.
