### ISSUE TITLE
Could support for the Enigma X1 XA7A75T-484 be reinstated in the future if new features are added?

### ISSUE THREAD

**Issue by 2292402583** [ufrisk/pcileech-fpga#173]
This is because the majority of FPGA development boards sold in China are designed based on the Enigma X1 XA7A75T-484, and most people are not aware that this chip has already ceased receiving updates and support.”

**Comment by ufrisk** [comment]
The original EnigmaX1 stopped selling years ago.

The vendors selling 75T boards don't sponsor this project in any meaningful way.

I guess I just don't see any reason why I should continue to sponsor other peoples commercial ventures for free. It's open source. But that doesn't mean I'm required to support other peoples businesses for free. The vendors selling these boards can provide support without my involvement.

Or they can sponsor this project in some meaningful way.

**Comment by ufrisk** [comment]
CaptainDMA which is a seller of 75T hardware have started to sponsor this project so the EnigmaX1 75T project is now reinstated.

There may be differences between the hardware though. The plan is to validate the CaptainDMA hardware in the next 1-2 months and publish a separate compatible project for them.

But for now the Enigma X1 75T project is back.

**Comment by 2292402583** [comment]
pardon me at my machine English,        It is exciting news, the reason I pulled the request last time was because I was looking for the source code for Cap75t, because cap75t and Enigma X1 are both XC7A75T. If you want to start developing projects for cap75t, Here is a project you may be interested in, this project has completed the development of cap75t. In addition, thank you for everything.      
    https://github.com/ekknod/pcileech-wifi
