### ISSUE TITLE
The purpose of the 'writemask.coe' file

### ISSUE THREAD

**Issue by maoxian123** [ufrisk/pcileech-fpga#177]
can anyone give an explanation？

**Comment by pubgdma** [comment]
Its to make your shadow config caps read only or writable

**Comment by ufrisk** [comment]
yep, it's to allow to set which parts are writable by the host system and which parts are not.

The Github issues sesion is more for raising issues around the project though, such as bugs and/or enhancement suggestions.

General questions are probably faster answered in the Discord channel.
