### ISSUE TITLE
Unable to retrieve required fpga device id

### ISSUE THREAD

**Issue by ggwpmaner** [ufrisk/pcileech-fpga#179]
Nothing shows at device manager and drvscan cant detect dma board.I’ve done the bios setting.
Before I flash ekkond wifi this board is multi audio controller.Now it’s gone.
My dma board is xc7a35t  ch347T 
CPU AMD 
---- FPGA DEVICE CONFIG REGISTERS: CORE-READ-ONLY     SIZE: 40 BYTES -----
0000    89 ab 00 00 28 00 00 00  04 0d 04 00 00 00 00 00   ....(...........
0010    34 de a5 95 02 00 00 00  34 de a5 95 02 00 00 00   4.......4.......
0020    00 00 02 00 ff ff ff ff                            ........

----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-WRITE    SIZE: 30 BYTES -----
0000    cd ef 04 00 1e 00 00 00  a0 86 01 00 00 00 00 00   ................
0010    ee 10 07 00 ee 10 66 06  02 bc 00 00 00 00         ......f.......

----- PCIe CORE Dynamic Reconfiguration Port (DRP)  SIZE: 0x100 BYTES -----
0000    00 00 00 01 00 02 01 00  11 40 00 00 00 00 00 00   .........@......
0010    ff e0 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020    00 00 00 00 00 00 00 00  00 00 00 40 00 00 00 00   ...........@....
0030    80 00 07 02 00 00 20 33  00 00 01 60 00 03 11 70   ...... 3...`...p
0040    03 f1 03 ff 01 00 3f fd  66 db 05 b6 01 00 00 50   ......?.f......P
0050    00 05 01 60 11 9c 00 00  00 00 00 00 00 00 00 00   ...`............
0060    00 00 10 60 00 12 40 21  00 4f 2d 50 00 03 00 00   ...`..@!.O-P....
0070    00 00 00 00 00 00 00 00  00 00 00 00 00 15 00 01   ................
0080    00 01 00 00 00 01 00 00  00 01 00 00 00 01 00 00   ................
0090    00 01 00 00 00 01 00 00  00 00 00 00 00 00 00 00   ................
00a0    00 00 00 00 01 40 11 60  00 02 02 e0 00 00 00 18   .....@.`........
00b0    00 04 20 01 00 11 00 00  00 00 00 00 00 01 00 00   .. .............
00c0    00 28 00 41 ff ff ff ff  00 e0 00 00 80 08 00 22   .(.A..........."
00d0    07 ff 03 52 02 48 00 08  00 40 0e 84 fa ac 00 00   ...R.H...@......
00e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.13,0000]
MemProcFS: Failed to connect to memory acquisition device

**Comment by ufrisk** [comment]
The PCIe parts of the register aren't showing so it makes me believe you don't even have the PCIe clock from the PCIe port. Is the PCIe port active on your target system?

Also I can recommend asking questions of general nature like this in the project discord server at:

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>

The issues section here at Github is more for reporting issues with the software as such rather than asking general questions.
