### ISSUE TITLE
I'm unable to join Discord. I really hope to join it.

### ISSUE THREAD

**Issue by fcmyoo** [ufrisk/pcileech-fpga#181]
Hey, big shot! I'm unable to join your Discord right now. Could you please let me join your Discord so that I can come in and learn something? My Discord ID is jxpro.

**Comment by ufrisk** [comment]
My mods asked you to stop advertising paid firmware services before you were banned. If you didn't stop it's on you not on me.

The discord server rules are there for a reason, I wish to personally stay out of troubles and also keep the server out of troubles.

Thank You for understanding.
