### ISSUE TITLE
Can I use pcileech-fpga in SP605 SDCard?

### ISSUE THREAD

**Issue by Gentle-Knife** [ufrisk/pcileech-fpga#2]
Can I use pcileech-fpga in FPGA SP605 SDCard? Xilinx FPGA SP605 can flash a linux boot image in its SDCard and boot from the image. But I think I need modify some code such as communicate with another device rather than FT601. So what's your advise? THX

**Comment by ufrisk** [comment]
I haven't tried that myself. To be honest I don't have much of a clue. 

The current design is quite simplistic though so you might be able to modify it to communicate with other devices over the FMC connector I suspect.
