### ISSUE TITLE
Detection vectors pciescreamer on target pc

### ISSUE THREAD

**Issue by finalmouse** [ufrisk/pcileech-fpga#20]
Hello,

I want to know if there is a scanning on the target computer. Which traces can they find?
Like I already changed the device/vendor id so it looks like a complete other device.

ps: is it possible to make it look like a 1080 gtx (if you have already one to look like a SLI setup

Are there any other traces in the memory of the target they know there is a pciscreamer in the PCIE slot?

**Comment by Flodkozza** [comment]
Nah dude ESEA's update is bs. They can't detect it if you know how does this work and how to get rid of all detection vectors. ( ex. if u have aim u need to have an undetected method for sending input, not the standard arduino, not gonna tell you how tho. )

**Comment by finalmouse** [comment]
Flodkozza, I know ESEA is just scaring people. My device didnt change from the start, thats why I got banned probably. I dont know about other vectors, I need info about that. I dont use aim no, radar only.
Can we talk in private somwhere?

Thankyou in advance

**Comment by finalmouse** [comment]
> 
> 
> Nah dude ESEA's update is bs. They can't detect it if you know how does this work and how to get rid of all detection vectors. ( ex. if u have aim u need to have an undetected method for sending input, not the standard arduino, not gonna tell you how tho. )

Flodkozza, I know ESEA is just scaring people. My device didnt change from the start, thats why I got banned probably. I dont know about other vectors, I need info about that. I dont use aim no, radar only.
Can we talk in private somwhere?

Thankyou in advance

**Comment by Flodkozza** [comment]
When did you change your IDs? I think ESEA has silently updated the AC about a week ago to collect data so if you played with original IDs in last 7-10 days, that is probably why you got banned. I also use radar only now because I don't wanna introduce more detection vectors tho. 

Honestly I don't see any other detection vectors besides the IDs if you do it right. Tho Ulf is alot smarter than me so hopefully he will know more 😆 

Tbh all accounts on other sites are the same name as my main account on esea so i wouldn't give that publicly as they do manually ban, so I can't talk privately 😛

**Comment by finalmouse** [comment]
> 
> 
> When did you change your IDs? I think ESEA has silently updated the AC about a week ago to collect data so if you played with original IDs in last 7-10 days, that is probably why you got banned. I also use radar only now because I don't wanna introduce more detection vectors tho.
> 
> Honestly I don't see any other detection vectors besides the IDs if you do it right. Tho Ulf is alot smarter than me so hopefully he will know more 😆
> 
> Tbh all accounts on other sites are the same name as my main account on esea so i wouldn't give that publicly as they do manually ban, so I can't talk privately 😛

Had original device/vendor till 17/10. After that I changed it to a broadcom. But all people with screamer/sp605 who used it few weeks ago till than banwave yesterday are banned.

Alot  of guys say there are more detections vectors when you use pcileech (like localhost) for radar but I cant believe that.

I just want to know how to spoof properly. I think I did but not sure 

![pcie](https://user-images.githubusercontent.com/43848127/47457313-0a90c380-d7d7-11e8-83bf-2a64cd917f05.PNG)

I know who you are and you also know who I am. So we can talk privately where we have no links ;)
We can help eachother out

**Comment by Flodkozza** [comment]
Just give me any of your usernames on any site and I'll contact you.

**Comment by finalmouse** [comment]
> 
> 
> Just give me any of your usernames on any site and I'll contact you.

add me steam? https://steamcommunity.com/id/5254218412854/

**Comment by finalmouse** [comment]
> 
> 
> Just give me any of your usernames on any site and I'll contact you.

talk discord? more private Sheepy#2937

**Comment by Flodkozza** [comment]
I don't use discord that often so I'm not sure how to find you xD Try to find me: PakiZaki#0279

I don't use voice chat tho.

**Comment by finalmouse** [comment]
> 
> 
> I don't use discord that often so I'm not sure how to find you xD Try to find me: PakiZaki#0279
> 
> I don't use voice chat tho.

accepted, you are offline tho

**Comment by helloboiss** [comment]
@Flodkozza you are still save on ESEA/faceit?
