### ISSUE TITLE
PCIe Screamer [content differs]

### ISSUE THREAD

**Issue by uppenbart** [ufrisk/pcileech-fpga#27]
Trying to flash prebuilt binary.

Warn : device needs paging or 4-byte addresses - not implemented
read 1512368 bytes from file pcileech_pciescreamer_top.bin and flash bank 0 at offset 0x00000000 in 1.315813s (1122.441 KiB/s)
contents differ
diff 0 address 0x00000085. Was 0x10 instead of 0x30
diff 1 address 0x0000009f. Was 0x01 instead of 0x13
diff 2 address 0x000000a0. Was 0x20 instead of 0x30
diff 3 address 0x000000a2. Was 0x00 instead of 0x80
diff 4 address 0x000000a3. Was 0x00 instead of 0x01
diff 5 address 0x000000a7. Was 0x01 instead of 0x09
diff 6 address 0x000000a8. Was 0x00 instead of 0x20
diff 7 address 0x000000ae. Was 0x80 instead of 0xc0
diff 8 address 0x000000b6. Was 0x80 instead of 0xa0
diff 9 address 0x000000ba. Was 0x00 instead of 0x05
....
diff 122 address 0x00000874. Was 0x00 instead of 0x30
diff 123 address 0x00000876. Was 0x00 instead of 0x20
diff 124 address 0x00000877. Was 0x00 instead of 0x01
diff 125 address 0x0000087b. Was 0x00 instead of 0x24
diff 126 address 0x0000087c. Was 0x00 instead of 0x30
diff 127 address 0x0000087d. Was 0x00 instead of 0x01
More than 128 errors, the rest are not printed.

anybody knows how to fix this? Using openocd on Ubuntu 18.04.

**Comment by tornado240** [comment]
use the version of openocd that ends with 28

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.
