### ISSUE TITLE
PCIeScreamer - VmmProc issue

### ISSUE THREAD

**Issue by uppenbart** [ufrisk/pcileech-fpga#30]
VmmProc doesn't work for me. Like I can read memory, probe succesfully, do everything. But VmmProc never seems to Initialize. At all.. :(

anybody have any tips. there isn't much to show as it just gets stuck on vmmproc.

**Comment by ufrisk** [comment]
Apologies for missing this issue.

Is it working right now? Also are you using the latest version of the MemProcFS for this? (old PCILeech implementation had known issues and is no longer supported).
