### ISSUE TITLE
PCIe Screamer Flash

### ISSUE THREAD

**Issue by ch1nw3ll** [ufrisk/pcileech-fpga#34]
My friend has asked me to look at this, but i use the sp605 so i don't have a clue.
Does this look like an ok flash? The "warn" near the top is a worry..
If it all looks ok, which button can he press to test all is ok?

Open On-Chip Debugger 0.10.0+dev-00653-g167cff09-dirty (2019-01-16-13:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
none separate
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
adapter speed: 10000 kHz
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 10000 kHz
Info : JTAG tap: xc7.tap tap/device found: 0x0362d093 (mfg: 0x049 (Xilinx), part: 0x362d, ver: 0x0)
loaded file bscan_spi_xc7a35t.bit to pld device 0 in 0s 229207us
Info : JTAG tap: xc7.tap tap/device found: 0x0362d093 (mfg: 0x049 (Xilinx), part: 0x362d, ver: 0x0)
Info : Found flash device 'micron n25q256 3v' (ID 0x0019ba20)
Warn : device needs paging or 4-byte addresses - not implemented
flash 'jtagspi' found at 0x00000000
auto erase enabled
Info : Found flash device 'micron n25q256 3v' (ID 0x0019ba20)
Warn : device needs paging or 4-byte addresses - not implemented
Info : Found flash device 'micron n25q256 3v' (ID 0x0019ba20)
Warn : device needs paging or 4-byte addresses - not implemented
Info : Found flash device 'micron n25q256 3v' (ID 0x0019ba20)
Warn : device needs paging or 4-byte addresses - not implemented
Info : sector 0 took 119 ms
Info : sector 1 took 124 ms
Info : sector 2 took 122 ms
Info : sector 3 took 118 ms
Info : sector 4 took 117 ms
Info : sector 5 took 119 ms
Info : sector 6 took 119 ms
Info : sector 7 took 119 ms
Info : sector 8 took 121 ms
Info : sector 9 took 118 ms
Info : sector 10 took 118 ms
Info : sector 11 took 117 ms
Info : sector 12 took 116 ms
Info : sector 13 took 120 ms
Info : sector 14 took 119 ms
Info : sector 15 took 119 ms
Info : sector 16 took 117 ms
Info : sector 17 took 119 ms
Info : sector 18 took 117 ms
Info : sector 19 took 119 ms
wrote 1310720 bytes from file pcileech_pciescreamer_top.bin in 16.316063s (78.450 KiB/s)
Info : Found flash device 'micron n25q256 3v' (ID 0x0019ba20)
Warn : device needs paging or 4-byte addresses - not implemented
read 1252128 bytes from file pcileech_pciescreamer_top.bin and flash bank 0 at offset 0x00000000 in 1.156874s (1056.970 KiB/s)
contents match
shutdown command invoked

Thanks

**Comment by ufrisk** [comment]
I have no idea, I'm not an OpenOCD expert.

But you can try to press the button SW3 to see if a LED blinks when you press it (then it's probably correctly flashed).

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.
