### ISSUE TITLE
Led on PCIeScreamer with Bitstream 4.0

### ISSUE THREAD

**Issue by mgoodings** [ufrisk/pcileech-fpga#36]
I noticed before one of the LED's would show the USB traffic, made it easy to see if the card was actually doing something, now it's just permanently on with the new bitstream.

**Comment by ufrisk** [comment]
Thanks. I confirm that this is a bug.

I'll fix this in the next release - which may be some weeks/month off. Meanwhile if the LED is absolutely necessary the previous version of the bitstream still works with PCILeech/MemProcFS as a temporary workaround.

**Comment by ufrisk** [comment]
I'm closing this issue. It should be resolved in the v4.1 version.
