### ISSUE TITLE
Flashing r02 screamer 

### ISSUE THREAD

**Issue by b3h3m07h** [ufrisk/pcileech-fpga#38]
How do I connect the JTAG flasher to the board? Do I need to solder on pins? The one I received is different then the one in your picture. This is what they sent me. 
![image](https://user-images.githubusercontent.com/7443730/69023968-9c84e480-0975-11ea-9add-2316ebd94056.jpg)
![image](https://user-images.githubusercontent.com/7443730/69023996-baeae000-0975-11ea-9848-d5b49c9fe82d.jpg)

**Comment by ufrisk** [comment]
hmm, if you only received that I understand why there is a problem. If you also received an adapter in the flash kit for 6-pin JTAG to 14-pin JTAG you could stick that in the holes on the PCIeScreamer and then put the lab cable on it. Or if you have a "male" 6x1 lab-cable you could use that as well, just stick it in the holes and it will be enough - no real need for soldering...

but I think you could have received something more in that kit, just buy something to fix it, or contact LambdaConcept.

**Comment by ufrisk** [comment]
I'm closing this issue since you seem to have it flashed and this seems to be a LambdaConcept distribution issue.
