### ISSUE TITLE
slow speeds @ sp605 with ft601

### ISSUE THREAD

**Issue by vac-porn** [ufrisk/pcileech-fpga#44]
> D:\pcileech_files>pcileech dump -min 0x0010000 -max 0x8000000
 Current Action: Dumping memory
 Access Mode:    Normal
 Progress:       127 / 127 (100%)
 Speed:          2015 kB/s
 Address:        0x0000000008000000
 Pages read:     32656 / 32752 (99%)
 Pages failed:   96 (0%)

![photo_2020-01-04_16-01-23](https://user-images.githubusercontent.com/32991800/71767336-a655ad80-2f0b-11ea-93b6-330b70709240.jpg)

using: pcileech_sp605_ft601_2_2_1.mcs
i tried every slot. 
i put also the card directly in the slots and that had the same results.
mainboard = https://www.asus.com/Motherboards/ROG-RAMPAGE-VI-EXTREME/specifications/
cpu = i9-7940x
ft601 driver installed plugged in to usb3 tried almost every slot.

**Comment by gcakir** [comment]
How did you solve it?
