### ISSUE TITLE
IEEE1394/Firewire

### ISSUE THREAD

**Issue by ksoju** [ufrisk/pcileech-fpga#48]
I know firewire is old school and limited to 32 bit addressing, but these cards are going for really cheap on ebay, aliexpress, etc. A lot of the cards that are compatible with pcileech are simply not readily available or quite expensive in general. Ever thought of supporting legacy 1394? Amazing work BTW!

**Comment by ufrisk** [comment]
I have no plans adding it. Main reason is it's just way too much work for me to add it (in hours I need to put in) for a legacy/dead protocol.

If you feel 32-bit is sufficient you could purchase the supported USB3380 board for $150 or so; or even better the NeTV2 board for $235 I think it is will give you access to the complete memory space.

If someone would like to contribute a firewire implementation in the form of a PCILeech "device"-file to my [LeechCore](https://github.com/ufrisk/LeechCore) project I would however gladly accept it.

Right now if you're looking into firewire there is the [Inception](https://github.com/carmaa/inception) project.
