### ISSUE TITLE
NeTV2 Not connecting.

### ISSUE THREAD

**Issue by njbrown09** [ufrisk/pcileech-fpga#50]
I try to connect with pcileech but im getting "Unable to connect to USB/FT601 device"

**Comment by ufrisk** [comment]
yes, but just posting "it's not working" without any information is worthless info for me to be able to give any help at all.

1. have you flashed the NeTV2?
2. can you ping the NeTV2?
3. what is your PCILeech command line?

**Comment by njbrown09** [comment]
1. Yes, i flashed it using the build instructions.
2. Yes, it gets an ip address with DHCP and i can ping it in windows.
3. https://gyazo.com/392fb300693cf5e1093ae83568f133f4

**Comment by njbrown09** [comment]
The NeTV2 is flashing the green light, and does not stop after 10 seconds (It does not go red). Id assume since it did get a dhcp address it is normal for the green flashing to never stop?

**Comment by ufrisk** [comment]
`pcileech.exe probe -device rawudp://ip=192.168.0.156 -v`

**Comment by njbrown09** [comment]
Thank you, i guess im dumb.
