### ISSUE TITLE
Failed to launch run 'impl_1' due to failures in the following run(s): bram_pcie_cfgspace_synth_1 

### ISSUE THREAD

**Issue by xNarkon** [ufrisk/pcileech-fpga#58]
Hello,

I have a problem while trying to build firmware ... I'm using Vivado 2020.1

I customized the Vendor and Device Identifiers by following: 
![image](https://user-images.githubusercontent.com/9370356/84401374-7c638e00-ac03-11ea-964d-43916c4e2a89.png)

And while building after a while I'm getting this error:
`ERROR: [Common 17-70] Application Exception: Failed to launch run 'impl_1' due to failures in the following run(s):
bram_pcie_cfgspace_synth_1
These failed run(s) need to be reset prior to launching 'impl_1' again.`

What can be wrong?

**Comment by ufrisk** [comment]
It may be due to the wizard unchecking some stuff on other pages - like the config space things when altering the values.

![image](https://user-images.githubusercontent.com/18221464/84435911-dc255d80-ac32-11ea-9db9-c49e8754ae6c.png)

**Comment by xNarkon** [comment]
Thanks for reply @ufrisk 

I think it's some kind different situation, I don't why but it cannot find this bram_pcie_cfgspace
![image](https://user-images.githubusercontent.com/9370356/84481125-e9bfff00-ac95-11ea-92ac-ebc87446585f.png)

The only thing I changed in Vivado 2020.1 Wizard were these ids :/

**Comment by xNarkon** [comment]
I found an issue, running bitstream building from Vivado itself is somehow broken, when made it run from the console, everything went flawlessly.
