### ISSUE TITLE
ScreamerM2 - cannot flash with openocd 

### ISSUE THREAD

**Issue by somethingisgo** [ufrisk/pcileech-fpga#59]
I purchased SCREAMER M.2 & JTAG SERIAL PACK from LambdaConcept.When using openocd to flash on win10,there is the following error:
Error: JTAG scan chain interrogation failed:all ones.
![error](https://user-images.githubusercontent.com/61864232/84460684-2c390a00-ac9d-11ea-93de-d288e19f1db5.png)

Is there any way to solve it?

**Comment by ufrisk** [comment]
You will need a special version of OpenOCD to flash the ScreamerM2 as described here and also in one of the other issue threads and on LambdaConcept page.

Also, I'm not really affiliated with LambdaConcept other than supporting the hardware the same way as I support the Xilinx dev boards, the USB3380 or the NeTV2 board so I'll have a really hard time helping you on this one :/

I use a HS2 JTAG cable compatible with Vivado myself so I'm not really that familiar with OpenOCD unfortunately.

**Comment by Beercow** [comment]
Interesting. I ran into the exact same thing. Not sure how to troubleshoot it.

**Comment by ufrisk** [comment]
LambdaConcept put up new instructions about how to flash with pre-compiled versions at https://docs.lambdaconcept.com/screamer/

Since this is not directly related to PCILeech itself I'm closing this issue. Good Luck with the flashing and I do recommend updating to v4.4 of the FPGA firmware if possible :)

**Comment by Beercow** [comment]
Thanks for the update. I think the my problem was I only had the programming cable plugged in. 😂
