### ISSUE TITLE
DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]

### ISSUE THREAD

**Issue by uranusb** [ufrisk/pcileech-fpga#60]
Hello,

I am using the NETV2 board and already flashed it successfully. I am able to ping the NeTV board. But when I run the following command:

E:\PCILeech>pcileech probe -device rawudp://192.168.0.222 -v

I got this error:

DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]
PCILEECH: Failed to connect to the device.

I don't know why did we get this error because we are not using USB to connect the NeTV2 board. Please help us to solve this problem. Thanks

**Comment by ufrisk** [comment]
please try:

`E:\PCILeech>pcileech probe -device rawudp://ip=192.168.0.222 -v`

**Comment by uranusb** [comment]
Issue resolved, thanks!

**Comment by ufrisk** [comment]
awesome, and good luck with your dma research :)

I'm closing this issue now since it's resolved.
