### ISSUE TITLE
FPGA SP605-FT601 flash use ISE Design Suite show " Flash was not programmed successfully"

### ISSUE THREAD

**Issue by Gentle-Knife** [ufrisk/pcileech-fpga#7]
I try to flash FPGA SP605-FT601 flash use ISE Design Suite with pcileech.mcs version 2.0 successfully, but flash with pcileech.mcs version 2.2 not successfully. What's wrong?
The flash print log show as follows:

 "-------------------------------------------------------------------"
" FLASHING BITSTREAM ONTO SP605 ...                                 "
" ENSURE SP605 IS CONNECTED TO PC WITH THE JTAG USB CABLE           "
" If command line flash does not work please use ISE iMPACT instead."
"-------------------------------------------------------------------"
Continue (Y/N): Y
Release 14.7 - iMPACT P.20131013 (nt64)
Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
Preference Table
Name                 Setting
StartupClock         Auto_Correction
AutoSignature        False
KeepSVF              False
ConcurrentMode       False
UseHighz             False
ConfigOnFailure      Stop
UserLevel            Novice
MessageLevel         Detailed
svfUseTime           false
SpiByteSwap          Auto_Correction
AutoInfer            false
SvfPlayDisplayComments false
INFO:iMPACT - Digilent Plugin: Plugin Version: 2.4.4
INFO:iMPACT - Digilent Plugin: no JTAG device was found.
AutoDetecting cable. Please wait.
*** WARNING ***: When port is set to auto detect mode, cable speed is set to
default 6 MHz regardless of explicit arguments supplied for setting the baud
rates
Connecting to cable (Usb Port - USB21).
Checking cable driver.
 Driver file xusb_emb.sys found.
 Driver version: src=1029, dest=1029.
 Driver windrvr6.sys version = 10.2.1.0. WinDriver v10.21 Jungo (c) 1997 - 2010 Build Date: Aug 31 2010 x86_64 64bit SYS
14:14:44, version = 1021.
 Cable PID = 0008.
 Max current requested during enumeration is 74 mA.
Type = 0x0004.
 Cable Type = 3, Revision = 0.
 Setting cable speed to 6 MHz.
Cable connection established.
Firmware version = 1303.
File version of D:/Xilinx/14.7/ISE_DS/ISE/data/xusb_xlp.hex = 1303.
Firmware hex file version = 1303.
PLD file version = 0012h.
 PLD version = 0012h.
Type = 0x0004.
ESN option: 000015776E4E01.
Identifying chain contents...'0': : Manufacturer's ID = Xilinx xc6slx45t, Version : 4
INFO:iMPACT:1777 -
   Reading D:/Xilinx/14.7/ISE_DS/ISE/spartan6/data/xc6slx45t.bsd...
INFO:iMPACT:501 - '1': Added Device xc6slx45t successfully.
----------------------------------------------------------------------
----------------------------------------------------------------------
'1': : Manufacturer's ID = Xilinx xccace, Version : 0
INFO:iMPACT:1777 -
   Reading D:/Xilinx/14.7/ISE_DS/ISE/acecf/data/xccace.bsd...
INFO:iMPACT:501 - '1': Added Device xccace successfully.
----------------------------------------------------------------------
----------------------------------------------------------------------
done.
Elapsed time =      0 sec.
Elapsed time =      0 sec.
Elapsed time =      0 sec.
Elapsed time =      0 sec.
Unprotect sectors: FALSE
INFO:iMPACT - A CFI file is not detected. To ensure correct and safe
   configuration,
    Please make sure a CFI file is present in the same directory as the PROM
   file,
    or, regenerate the PROM file with the latest software.
Maximum TCK operating frequency for this device chain: 16700000.
Validating chain...
Boundary-scan chain validated successfully.
'2': SPI access core not detected. SPI access core will be downloaded to the
device to enable operations.
INFO:iMPACT - Downloading core file
   D:/Xilinx/14.7/ISE_DS/ISE/spartan6/data/xc6slx45t_spi.cor.
'2': Downloading core...
 LCK_cycle = NoWait.
LCK cycle: NoWait
done.
'2': Reading status register contents...
INFO:iMPACT:2219 - Status register values:
INFO:iMPACT - 0011 1100 1110 1100
INFO:iMPACT:2492 - '2': Completed downloading core to device.
'2': IDCODE is 'ef4017' (in hex).
'2': ID Check passed.
'2': IDCODE is 'ef4017' (in hex).
'2': ID Check passed.
'2': Erasing Device.
'2': Using Sector Erase.
'2': Erasing non-volatile quad-enable bit...
'2': Programming Flash.
'2': Reading device contents...
done.
'2': Verification completed.
INFO:iMPACT - File pcileech.cfi does not exist.
'2':Programming in x1 mode.
W25Q64BV Status Register Contents = 0x0000.
QUAD ENABLE                                       :         0
STATUS REGISTER PROTECT 1                         :         0
STATUS REGISTER PROTECT 0                         :         0
SECTOR PROTECT                                    :         0
TOP/BOTTOM PROTECT                                :         0
BLOCK PROTECT BIT 2                               :         0
BLOCK PROTECT BIT 1                               :         0
BLOCK PROTECT BIT 0                               :         0
'2': Configuration data download to FPGA was not successful. DONE did not go
high, please check your configuration setup and mode settings.
INFO:iMPACT - '2': Flash was not programmed successfully.
Elapsed time =    164 sec.
----------------------------------------------------------------------
----------------------------------------------------------------------

**Comment by ufrisk** [comment]
I have to look into this. Unfortunately I'll get my SP605 board back next week. Until then please use the 2.0 version of the bitstream.

For the SP605, the changes aren't that big - the 2.0 version of the bitstream will work meanwhile, most notably is faster load time, which is nice but not a must.

**Comment by ufrisk** [comment]
Apologies for the delay, but I hope it should be fixed now. It's the same binary bitstream but a supporting file was missing.
Please let me know if it works better now.

**Comment by 0x4e38** [comment]
Still have same issue with the latest version.

**Comment by ufrisk** [comment]
@0x4e38 I do not have the same issue unfortunately which makes this a bit harder to "debug".

What kind of setup are you running and which error are you getting?

I just tested this on my Windows 7 x64 system running Xilinx ISE Webpack 14.7.

Install Xilinx ISE Development Environment. (14.7 webpack)
Download and unzip pre-built binary:  pcileech_sp605_ft601_2_2_1.mcs .zip 
Open ISE Design Suite 64-Bit Command Prompt.
Make sure the JTAG USB cable is connected.
Run flash.bat to flash the bitstream onto the SP605.
Finished !!!

**Comment by ufrisk** [comment]
@0x4e38 apologies for the late answer, I mistakenly formatted the wrong disk the other week and it took some time to re-install everything since it's been a bit busy irl...

Anyway I get the same error as you if the file `pcileech.cfi` is not in the same directory as the `flash.bat`, `pcileech.mcs` and `pcileech_impact_config.txt`

Can you please confirm that you have downloaded the latest version from [here](https://mega.nz/#!QPJm3bLT!8NrEBR-yLn-Qur7VkqsnahiPgkGp2nWw4Z9XWLLamxo), and that you unzipped all conents of the zip into a directory and that you open the ISE Design Suite 64-Bit Command Prompt, cd into the directory containing the unzipped files and run `flash.bat`.

**Comment by 0x4e38** [comment]
@ufrisk thanks for your reply,  I tried it again, but got same error.

**Comment by ufrisk** [comment]
@0x4e38 auch, then I just don't know what is wrong. Can you please try to build the project from sources as per the instructions and then use the flash.bat from the project repo?

Unfortunately building takes a good while, but it will be interesting to see if it works (if so then I could at least update the instructions in the readme for others).

**Comment by 0x4e38** [comment]
@ufrisk OK, I will try to build it.

**Comment by ufrisk** [comment]
I'm closing this issue since it's now resolved.
