### ISSUE TITLE
MmWin_MemCompress_InitializeVirtualStorePageFileNumber: CANNOT READ ntoskrnl.exe .data SECTION.

### ISSUE THREAD

**Issue by PPhilippGit** [ufrisk/pcileech-fpga#70]
Hello :)

We are having an issue with Windows 2004.

Usually the Windows 2004 #3 problem gets solved by replacing the vmm.dll 
However sometimes after replacing it this error pops up: 
**"MmWin_MemCompress_InitializeVirtualStorePageFileNumber: CANNOT READ ntoskrnl.exe .data SECTION."**
This error is really random and comes and goes as it wishes - sometimes it's instantly there after a coldboot and sometimes it works for a bit and just suddenly appears without any reason - There were a few times where it disappeared without a reboot as well.

We have not been able to figure out any pattern/fix to it except for rolling back a few windows updates or completely reverting to a 1909 build. 
This happens on all sorts of mainboards/chipsets spread from AMD to Intel, old and new.
It only appears on Windows10 2004.

I am raising this ticket in hopes that there is a known setting/fix for it except for reinstalling windows.

Regards,
Philipp

**Comment by ufrisk** [comment]
1. What do you mean by replacing vmm.dll? I would recommend always using the most recent versions of all my .dll / .exe files such as packaged under my releases section.

2. The message you're receiving is mostly a warning message. It's not for some reason to read the full .data section of the kernel. It needs to do this to detect if there is a non-standard location for the "compressed store" containing compressed memory. By default the default location is selected and things should be fine in most cases. Are you experiencing any additional issues after this error message?

Also, another way to "resolve" this issue would be to place the dbghelp.dll and symserv.dll (as packaged in my MemProcFS binary installation) alongside the vmm.dll - this will allow the download of symbol files from the Microsoft symbol server - bypassing the need for this lookup.

Anyway, it's interesting it only seems to apply to Win10 2004. I lost access to MSDN which I had from Microsoft so my testing on 2004 aren't as good as I would like. Are you able to take a memory dump file with PCILeech from an affected system where the error occurs. Please note that memory dumps may contain sensitive information such as passwords so best would be from a test system.

**Comment by PPhilippGit** [comment]
Sorry for opening the issue.

it was a misunderstanding of my part.
