### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by bloddy** [ufrisk/pcileech-fpga#86]
Hi there, first of all thank you for this .. and all hardworking.

Now, I would like to understand how the cfg space is addressed because if I try to modify it... the base one it's all the time overwritten by the vivado ... the extend I've seen that we can use the cfg that is here and modify it.

Maybe I'm wrong or I don't understand how it should work ... but when I'm generating an image all the time i have the almost the same data....

Not an issue but more an noob information ..

**Comment by ufrisk** [comment]
The parts that are overwritten by Vivado are unfortunately only possible to change by configuring individual values in the PCIe core configuration wizard inside of Vivado. It sucks; but it's unfortunately the way things are right now.
