### ISSUE TITLE
ScreamerM2 "Invalid property name 'platform.description'."

### ISSUE THREAD

**Issue by KeganHollern** [ufrisk/pcileech-fpga#91]
`ERROR: [Common 17-142] Invalid property name 'platform.description'.  Please use the 'list_property' command to find properties supported by the target 'project' object.`

Following the instructions for building the gateware, using Vivado 2018.3, running the command `source vivado_generate_project.tcl -notrace` leads to the above error message.

**Comment by ufrisk** [comment]
Hi,

You'd need to use Vivado 2020.2 (there is a 2020.3 version as well; but don't use that one since it's not supporting artix-7).

Please let me know if you have better luck with it. Also do I still have references to 2018.3 in my documentation still somewhere?
