### ISSUE TITLE
Open Source DMA hardware????

### ISSUE THREAD

**Issue by huangfengye** [ufrisk/pcileech-fpga#96]
Hi, if anyone tried this Open Source DMA hardware??
https://github.com/FotatoPotato/Artix-Express-35

**Comment by ufrisk** [comment]
Thanks. I was not aware. It seems like a device similar to the PCIeScreamerR04 but more geared towards development.

**Comment by KengKengu** [comment]
Should the software work with a device like this?

https://rhsresearch.com/products/litefury

It's not on the list in the README but I don't see why it would not work.

**Comment by ufrisk** [comment]
@KengKengu The software works with the LiteFury, but you'd need additional hardware for PCILeech to communicate with it over USB. I detail this in this blog entry: http://blog.frizk.net/2021/10/acorn.html

**Comment by KengKengu** [comment]
Thank you very much, that was very informative and I am grateful. Unfortunately I am not sure if I can complete all the steps. The biggest issue I have is removing the 3.3V to 2.5V voltage regulator, as I don't have the required tools. 

Do you think there is any way I could remove it without the hot-air rework station?
Otherwise I will have to use the another way to communicate, which would be much slower.

**Comment by ufrisk** [comment]
Maybe there are other USB modules; but my guess is that it would involve significant work to get it working. I'm not going to help with that. Unfortunately the Nitefury just isn't very suitable for PCILeech DMA accesses. You're probably better off purchasing a Screamer or EnigmaX1 board (when they get in stock).

**Comment by olealgoritme** [comment]
The acorn blogpost was awesome! Will be trying this soon with my acorns:) 

One thing though, the link in the post doesn't exist:
https://github.com/ufrisk/pcileech-fpga/acorn/

**Comment by ufrisk** [comment]
@olealgoritme Thank you for pointing this out. I've updated the link in the blog post to the correct project pages.

**Comment by ufrisk** [comment]
I'm closing this thread due to old age. Nothing has changed with regards to open source hardware as far as I know.

But, there are some lower cost options available. One example is the DMANinja https://www.aliexpress.com/item/1005004823146314.html
